In [39]:
import pandas as pd


Loading the raw data file
---

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [57]:
file_path = "/content/drive/MyDrive/Lion-Biologging-SoS'26/lion_data.csv"
df = pd.read_csv(file_path)
df.head()

,event-id,visible,timestamp,location-long,location-lat,eobs:temperature,gps:dop,height-raw,sensor-type,individual-taxon-canonical-name,tag-local-identifier,individual-local-identifier,study-name,study-timezone,study-local-timestamp
0,33042889052,True,2008-12-15 05:00:00.000,23.650275,-21.225109,29,1.8,987.00,gps,Panthera leo,GSM05751,1003,African Lion - Panthera Lion Central Kalahari ...,GMT+02:00,2008-12-15 07:00:00.000
1,33042889053,True,2008-12-15 06:00:00.000,23.655901,-21.221622,30,2.0,983.90,gps,Panthera leo,GSM05751,1003,African Lion - Panthera Lion Central Kalahari ...,GMT+02:00,2008-12-15 08:00:00.000
2,33042889054,True,2008-12-15 07:00:00.000,23.659498,-21.220391,31,1.8,978.80,gps,Panthera leo,GSM05751,1003,African Lion - Panthera Lion Central Kalahari ...,GMT+02:00,2008-12-15 09:00:00.000
3,33042889055,True,2008-12-15 08:00:00.000,23.659542,-21.220418,33,3.4,990.30,gps,Panthera leo,GSM05751,1003,African Lion - Panthera Lion Central Kalahari ...,GMT+02:00,2008-12-15 10:00:00.000
4,33042889056,True,2008-12-15 09:00:00.000,23.659813,-21.221464,35,2.2,987.63,gps,Panthera leo,GSM05751,1003,African Lion - Panthera Lion Central Kalahari ...,GMT+02:00,2008-12-15 11:00:00.000

In [58]:
#dropping useless columns
try:
  df = df.drop(columns=['timestamp','event-id','visible','eobs:temperature','gps:dop','height-raw','sensor-type','individual-taxon-canonical-name','study-name','study-timezone','tag-local-identifier'])
except:
  df = pd.read_csv(file_path)
  df = df.drop(columns=['timestamp','event-id','visible','eobs:temperature','gps:dop','height-raw','sensor-type','individual-taxon-canonical-name','study-name','study-timezone','tag-local-identifier'])
df.head()

,location-long,location-lat,individual-local-identifier,study-local-timestamp
0,23.650275,-21.225109,1003,2008-12-15 07:00:00.000
1,23.655901,-21.221622,1003,2008-12-15 08:00:00.000
2,23.659498,-21.220391,1003,2008-12-15 09:00:00.000
3,23.659542,-21.220418,1003,2008-12-15 10:00:00.000
4,23.659813,-21.221464,1003,2008-12-15 11:00:00.000

In [59]:
#changing names to simplify
df = df.rename(columns={'study-local-timestamp':'local_time','individual-local-identifier':'lion_id','location-lat':"latitude",'location-long':'longitude'})
df.head()

   longitude   latitude  lion_id               local_time
0  23.650275 -21.225109     1003  2008-12-15 07:00:00.000
1  23.655901 -21.221622     1003  2008-12-15 08:00:00.000
2  23.659498 -21.220391     1003  2008-12-15 09:00:00.000
3  23.659542 -21.220418     1003  2008-12-15 10:00:00.000
4  23.659813 -21.221464     1003  2008-12-15 11:00:00.000

In [60]:
#finding and replacing corrupted values
has_nan = df.isna().any().any()
print(has_nan)
#the data we have is already very refined

False

In [61]:
#converting timestamp sting into datetime object
df['local_time'] = pd.to_datetime(df['local_time'])
df.head()

   longitude   latitude  lion_id          local_time
0  23.650275 -21.225109     1003 2008-12-15 07:00:00
1  23.655901 -21.221622     1003 2008-12-15 08:00:00
2  23.659498 -21.220391     1003 2008-12-15 09:00:00
3  23.659542 -21.220418     1003 2008-12-15 10:00:00
4  23.659813 -21.221464     1003 2008-12-15 11:00:00

In [62]:
#sorting the rows based on priority(id then time)
df = df.sort_values(by=['lion_id','local_time']).reset_index(drop=True)
df.head(15)

    longitude   latitude  lion_id          local_time
0   22.743834 -21.286005     1001 2009-12-07 21:30:00
1   22.743923 -21.286270     1001 2009-12-07 22:00:00
2   22.743892 -21.286271     1001 2009-12-07 22:30:00
3   22.743892 -21.286279     1001 2009-12-07 23:00:00
4   22.743894 -21.286264     1001 2009-12-07 23:30:00
5   22.743804 -21.286048     1001 2009-12-08 00:00:00
6   22.744135 -21.287131     1001 2009-12-08 00:30:00
7   22.744277 -21.287271     1001 2009-12-08 01:00:00
8   22.744237 -21.287307     1001 2009-12-08 01:30:00
9   22.744216 -21.287307     1001 2009-12-08 02:00:00
10  22.744069 -21.286708     1001 2009-12-08 04:00:00
11  22.743816 -21.286015     1001 2009-12-08 04:30:00
12  22.743839 -21.286599     1001 2009-12-08 05:00:00
13  22.743831 -21.286609     1001 2009-12-08 05:30:00
14  22.743853 -21.286584     1001 2009-12-08 06:00:00

In [63]:
#saving the clean csv file
df.to_csv("/content/drive/MyDrive/Lion-Biologging-SoS'26/lion_data_clean.csv", index=False)